### ISSUE TITLE
Collate, combine, spread ... operator

### ISSUE THREAD

**Issue by ComLock** [gajus/pianola#5]
I'm using surgeon in this example, but the idea should be good for pianola.

Given

```html
<body>
  <a href="/relative1">Relative 1</a>
  <a href="/relative2">Relative 2</a>
  <a href="/relative1">Relative1 Duplicate</a>
  <a href="http://www.example.com/relative1">Absolute a duplicate of Relative1 after resolve</a>
</body>
```

What I want to do is return an array with resolved urls and remove duplicates.

```yaml
uniqueAbsoluteLinks: sa 'body a:not([href^="#"]'|sa href|resolve http://www.example.com/ ... uniq
```

Result:
```javascript
{
  links: [
    'http://www.example.com/relative1',
    'http://www.example.com/relative2'
  ]
}
```

What happens here is that
* 'sa href' is executed once per link element
* resolve is executed once per returned href string
* all the resolved href strings are combined to an array
* and uniq is executed once on the whole array

Another alternative syntax would be parentheses, but its not as pretty:

```yaml
uniqueAbsoluteLinks: sa 'uniq(body a:not([href^="#"]'|sa href|resolve)
```

**Comment by ComLock** [comment]
You could use ">" or ">>" like in terminal redirects, but that looks a bit similar to the CSS direct child selector.

And since pianola is a javascript tool going with operators similar to javascript should be intuitive.

ref:
https://www.w3schools.com/cssref/css_selectors.asp
https://robots.thoughtbot.com/input-output-redirection-in-the-shell

**Comment by gajus** [comment]
@ComLock Can you raise a PR for this?

In principle, I like this.

**Comment by ComLock** [comment]
I can try :) (But I don't know when, cause I'm working on multiple projects.)

**Comment by joepie91** [comment]
I feel like perhaps marking a subroutine as 'low-level' - that is, with direct access to the result set, as opposed to being applied to each individual result - would be a good solution for both this scenario, as well as for 'escape hatch' scenarios where you need to somehow work around the semantics of pianola.

One of my ideas was to have something similar to what's suggested above with `...`, but specifying it as a marker on the subroutine call:

```
regularSubroutine | otherRegularSubroutine | @lowLevelSubroutine
```

... however, on second thought, this may not make a lot of ergonomic sense - you'd have to specify that marker on every invocation, forgetting it would make it fail in a confusing way, and are there really any scenarios where you'd want to invoke a subroutine in both a low-level and high-level way depending on context?

I feel like perhaps "this subroutine is low-level" is an attribute *of the subroutine*, not of the invocation; so instead, something like this on define time may be more appropriate:

```js
surgeon({
	regularSubroutine: function(...) {
		// ...
	},
	otherRegularSubroutine: function(...) {
		// ...
	},
	lowLevelSubroutine: surgeon.lowLevel(function(...) {
		// ...
	}),
})
```

(Note the `surgeon.lowLevel` marker.)

This would then result in usage like this:

```
regularSubroutine | otherRegularSubroutine | lowLevelSubroutine
```

... where the exact implementation details of `lowLevelSubroutine` are obscured from the call site, and it can be used like any other subroutine. That would be a lot less confusing, I think.

(Alternatively, an `@` prefix or so could still be required for low-level subroutines, if you want to make it clear at the call-site as well that a subroutine can only be used in a low-level sense. But that'd be *in addition to* the declaration marker.)

**Comment by ComLock** [comment]
Another thought is how Perl6 return value works. Everything is an object. When you return lets say the string 'hello', it's value can be resolved in different contexts. Possibly multiple at the same time. It's up to the operators which context of an object is interesting. So the string 'hello' has a Boolean context with the value true. So if you returned an iterator one would have access to both a single instance, it's index and the full array.

**Comment by gajus** [comment]
https://github.com/gajus/pianola#the-aggregate-pipeline-operator-

@ComLock, @joepie91 Does this solve your issues?

**Comment by ComLock** [comment]
@gajus I don't think it does, gotta test some more, it might make better workarounds possible though.

I want the sortUniq function to receive an array, which is still does not:
```yaml
links: sa 'a:not([href^="#"])' | ra href | resolve https://www.iana.org/domains/reserved >| sortUniq
```

But I should be able to make new subroutines that process and return arrays:
```yaml
links: sa 'a:not([href^="#"])' >| processArrayReadAttributeAndReturnArray href >| processArrayResolveAndReturnArray https://www.iana.org/domains/reserved >| sortUniq
```

**Comment by ComLock** [comment]
You might want to make most subroutines "arraySafe".

```javascript
const ar = (subject, values, bindle) => Array.isArray(subject)
	? subject.map(s => readSubroutine(s, values, bindle))
	: readSubroutine(subject, values, bindle);

const operate = surgeon({
	evaluator: cheerioEvaluator(),
	subroutines: {
		...subroutineAliasPreset,

		ar,
		ara: (s, [attributeName], b) => ar(s, ['attribute', attributeName], b),
		arp: (s, [propertyName], b) => ar(s, ['property', propertyName], b)
	}
};
```

**Comment by ComLock** [comment]
As long as I make my subroutines "arraySafe" and only use the aggregate pipeline operator this works well. In fact it seems to be faster too. I'm guessing processing a single array rather than calling a lot of functions will do that.

**Comment by gajus** [comment]
> I want the sortUniq function to receive an array, which is still does not:

There is no way to achieve this (logically) unless you add some sort of grouping of the queries, i.e. `()`.

**Comment by ComLock** [comment]
Parentheses does look similar to sub shell in the terminal too. But for my usecase aggregate pipeline operator works fine.
